### ISSUE TITLE
UI Cloud Controller integration

### ISSUE THREAD

**Issue by vb-mnsnd** [Art-of-WiFi/UniFi-API-browser#106]
Hi there,

Can UniFi-API-browser pull data from a controller that is hosted on UI Cloud unifi.ui.com?
We are about to move our controller to UI Cloud and we want to implement UniFi-API-Browser to pull usage data for us.

**Comment by malle-pietje** [comment]
Actually, when using a cloud-based UniFi controller, you will always have a way to connect to it directly. UI's cloud is no different, AFAIK, other than that they run the UniFi OS version of the Network Application.

You must use the public IP address or hostname that you get from the provider, not the unifi.ui.com address, because that isn't supported by our API tools.

**Comment by vb-mnsnd** [comment]
Then it should be the same address address as Inform URL. It looks like this https://<actual_controller>.unifi-hosting.ui.com
Would it work?

**Comment by malle-pietje** [comment]
Yes, that looks fine. Make sure to use port 443 in this case.
