### ISSUE TITLE
Not Working On Server

### ISSUE THREAD

**Issue by AjaySharma101** [Art-of-WiFi/UniFi-API-browser#44]
Hello,
Thanks for your API Browser. 
Its working on localhost.
But not working on server.
Please Any Idea...

**Comment by malle-pietje** [comment]
You're welcome!

I'm assuming you wish to connect from the server running the API browser tool to another server running the UniFi controller, correct?

In that case, are you using the correct URL (with correct IP address or FQDN) to connect to the controller? Maybe there is a firewall in between the two?

Otherwise please submit more details such as the exact error in your browser and the relevant lines from your web server error logs for the server where the API browser is running. Without that, I am just guessing...
