### ISSUE TITLE
API IP from VPN

### ISSUE THREAD

**Issue by klarlichter** [Art-of-WiFi/UniFi-API-browser#91]
Hello, is it possible to display IP who is set on vpn connection? 
And also possible to update that IP via API?

**Comment by malle-pietje** [comment]
Not sure what you mean but the VPN configuration (when created as a network and not through the `config.gateway.json` file) is available through the list_networkconf() method.

**Comment by klarlichter** [comment]
Hello, yes thats true I can see ""purpose": "site-vpn"," under network... is there any possibility to udpdate the value 
"ipsec_local_ip": "*.*.*.*",
"ipsec_peer_ip": "*.*.*.*",

via API and will update enough or it need also some restart to initilize the new parameter?

**Comment by malle-pietje** [comment]
I haven't done this myself before so can't tell from experience. The steps I suggest you follow are these:

1. open your browser developer tools (Ctrl + Shift + 1 in Chrome)
2. open the network tab in the developer tools and select Fetch/XHR
3. create or update a VPN configuration through the controller web interface
4. look in de developer tools to see which API URL is called and what the payload looks like
5. check in the API Client class source code to see whether one of the existing methods uses the same URL, my guess is it will be `set_networksettings_base()` or `create_network()` depending on the action.
6. call the method needed with the correct payload that is needed to achieve what you want.

I can't help you further than this I'm afraid because it quickly becomes too specific.

If you update/create a VPN through the API it has the same effect as when doing it through the controller web interface. So if there is no need to perform a restart when doing it through the web interface, the same applies when applying the change through the API. This is the main benefit of using the API versus direct access to the MongoDB database.

**Comment by klarlichter** [comment]
Hello, i think as I can see it is set_networksettings_base()... but how I can set that? 
If I run list_networkconf() I can see 

 { "_id": "60d8b2a15c18e3613338fca7", "purpose": "site-vpn", "ipsec_interface": "wan", "enabled": false, "vpn_type": "ipsec-vpn", "route_distance": 30, "ipsec_profile": "customized", "remote_vpn_subnets": [ "*.*.*.*\/24" ], "name": "Site-2-Site", "ipsec_key_exchange": "ikev2", "ipsec_encryption": "aes256", "ipsec_hash": "sha1", "ipsec_dh_group": 14, "ipsec_ike_dh_group": 14, "ipsec_esp_dh_group": 14, "ipsec_pfs": true, "ipsec_dynamic_routing": true, "x_ipsec_pre_shared_key": "****", "ipsec_local_ip": "*.*.*.*", "ipsec_peer_ip": "*.*.*.*", "is_nat": false, "site_id": "60bf3d079b525e0eb95379a6", "ifname": "vti64" }

But how I can update parameter ipsec_peer_ip for example by runnig  set_networksettings_base()

**Comment by malle-pietje** [comment]
I can't teach you how to work with PHP, so please read the source code for set_networksettings_base() to better understand what needs to be done:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L2479-L2492

It's actually pretty basic PHP stuff. Also, look through some of the examples.

**Comment by klarlichter** [comment]
Hello, thanks... I was take a loook....

Also was take alook what i need...

And I was setup that

$network_id = "60d8b2a15c18e3613338fca7";
$update_vpn = [
            'ipsec_local_ip' => '8.8.8.8'",
            'ipsec_peer_ip' => '8.8.4.4'
];

$update_device    = $unifi_connection->set_networksettings_base($network_id, $update_vpn);


But it seems wrong... please allow one time help. :(

**Comment by klarlichter** [comment]
It is done thanks. :)
